apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
  namespace: crawler
data:
  CRAWLER_DB_PATH: "/cache/db"
  CRAWLER_KEYWORDS: "chat,sync,messaging"
  CRAWLER_PORT_2: "8081"
  CRAWLER_PORT_3: "8082"