apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-web
  labels:
    app: synergychat-web
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: synergychat-web
    spec:
      containers:
        - name: synergychat-web
          image: docker.io/bootdotdev/synergychat-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WEB_PORT
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: WEB_PORT
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: API_URL
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
